---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ${K8S_NAMESPACE}-${CONTEXT}-${BRANCH_HASH}
        git/branch: ${BRANCH_NAME}
      annotations:
        git/commit: ${COMMIT}
        gitlab/job: "${JOB_ID}"
    spec:
      containers:
        - image: ${IMAGE_NAME}:${IMAGE_TAG}
          name: ${K8S_NAMESPACE}-${CONTEXT}
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 8080
          env:
          - name: HASURA_GRAPHQL_DATABASE_URL
            value: "postgres://postgres@${POSTGRES_HOST}/${POSTGRES_DATABASE}"
          - name: HASURA_GRAPHQL_ENABLE_CONSOLE
            value: "true"
          - name: HASURA_GRAPHQL_ADMIN_SECRET
            value: "secret"
          - name: HASURA_GRAPHQL_JWT_SECRET
            value: "{\"type\": \"RS256\",\"jwk_url\": \"http://${K8S_NAMESPACE}-api-${BRANCH_HASH}/api/v2/auth/jwks\"}"
          - name: WHATEVER_URL
            value: "http://${K8S_NAMESPACE}-graphql-server-${BRANCH_HASH}"
