apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels:
{{ include "nodejs.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nodejs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations: {}
      labels: {}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 10
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 10
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:
            - name: APP_URL
              value: {{ required "domain must be defined" .Values.appURL }}
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: HASURA_GRAPHQL_ADMIN_SECRET
            - name: HASURA_WEB_HOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: HASURA_WEB_HOOK_SECRET
            - name: PGSSLMODE
              value: require
            - name: HASURA_GRAPHQL_URI
              value: 'http://hasura/v1/graphql'
            - name: DATABASE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DATABASE_CONNECTION
            - name: DATABASE_URL
              value: $(DATABASE_CONNECTION)/{{ required "dbName must be specified" .Values.dbName }}
            - name: PORT
              value: '4000'
            - name: NODE_ENV
              value: production
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SMTP_PASS
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SMTP_FROM
            - name: SENTRY_PUBLIC_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: SENTRY_PUBLIC_DSN
            - name: AZURE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: AZURE_ACCOUNT_NAME
            - name: AZURE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: AZURE_ACCOUNT_KEY
            - name: OCMI_SYNC_FILE_ENABLED
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: OCMI_SYNC_FILE_ENABLED
            - name: OCMI_FILE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: OCMI_FILE_PASSWORD
            - name: SENTRY_ENV
              value: '${NODE_ENV}'
            - name: AUTH_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: AUTH_PRIVATE_KEY
            - name: AUTH_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: AUTH_PUBLIC_KEY