{{- $fullName := include "nodejs.fullname" . -}}
apiVersion: extensions/v1beta1
# apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "nodejs.labels" . | indent 4 }}
  annotations:
{{ .Values.ingress.annotations | toYaml | indent 4 }}
spec:
  tls:
    - hosts:
        - {{ .Values.host | quote }}
      secretName: {{ .Values.tlsSecretName }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
        - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 3000
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{ $fullName }}
          #       port:
          #         number: 3000
