{{- $fullName := include "nodejs.fullname" . -}}
# apiVersion: extensions/v1beta1
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "nodejs.labels" . | indent 4 }}
  annotations:
{{ .Values.ingress.annotations | toYaml | indent 4 }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: deny";
      more_set_headers "X-XSS-Protection: 1; mode=block";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Content-Security-Policy: default-src https://matomo.fabrique.social.gouv.fr/; connect-src *.dev.fabrique.social.gouv.fr https://api-emjpm.fabrique.social.gouv.fr/api/ https://emjpm.fabrique.social.gouv.fr https://hasura-emjpm.fabrique.social.gouv.fr/v1/graphql https://matomo.fabrique.social.gouv.fr/ https://openmaptiles.geo.data.gouv.fr/ https://openmaptiles.github.io/ https://api-adresse.data.gouv.fr https://entreprise.data.gouv.fr https://nominatim.openstreetmap.org; font-src 'self'; img-src  https://openmaptiles.github.io/ https://api.mapbox.com/ 'self' data: blob:; script-src https://matomo.fabrique.social.gouv.fr/ blob: 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://api.tiles.mapbox.com/;"; manifest-src 'self';
spec:
  tls:
    - hosts:
        - {{ .Values.host | quote }}
      secretName: {{ .Values.tlsSecretName }}
  rules:
    - host: {{ .Values.host | quote }}
      http:
        paths:
        # - path: /
        #   backend:
        #     serviceName: {{ $fullName }}
        #     servicePort: 3000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: 3000
